// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: service.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckNode_Register_FullMethodName        = "/checknode.CheckNode/Register"
	CheckNode_SubscribePolicy_FullMethodName = "/checknode.CheckNode/SubscribePolicy"
	CheckNode_ReportEvent_FullMethodName     = "/checknode.CheckNode/ReportEvent"
	CheckNode_Heartbeat_FullMethodName       = "/checknode.CheckNode/Heartbeat"
)

// CheckNodeClient is the client API for CheckNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckNodeClient interface {
	Register(ctx context.Context, in *SlaveInfo, opts ...grpc.CallOption) (*RegistrationResponse, error)
	SubscribePolicy(ctx context.Context, in *SlaveID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Policy], error)
	ReportEvent(ctx context.Context, in *EventLog, opts ...grpc.CallOption) (*Empty, error)
	Heartbeat(ctx context.Context, in *SlaveID, opts ...grpc.CallOption) (*Empty, error)
}

type checkNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckNodeClient(cc grpc.ClientConnInterface) CheckNodeClient {
	return &checkNodeClient{cc}
}

func (c *checkNodeClient) Register(ctx context.Context, in *SlaveInfo, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, CheckNode_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkNodeClient) SubscribePolicy(ctx context.Context, in *SlaveID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Policy], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CheckNode_ServiceDesc.Streams[0], CheckNode_SubscribePolicy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SlaveID, Policy]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CheckNode_SubscribePolicyClient = grpc.ServerStreamingClient[Policy]

func (c *checkNodeClient) ReportEvent(ctx context.Context, in *EventLog, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CheckNode_ReportEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkNodeClient) Heartbeat(ctx context.Context, in *SlaveID, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CheckNode_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckNodeServer is the server API for CheckNode service.
// All implementations must embed UnimplementedCheckNodeServer
// for forward compatibility.
type CheckNodeServer interface {
	Register(context.Context, *SlaveInfo) (*RegistrationResponse, error)
	SubscribePolicy(*SlaveID, grpc.ServerStreamingServer[Policy]) error
	ReportEvent(context.Context, *EventLog) (*Empty, error)
	Heartbeat(context.Context, *SlaveID) (*Empty, error)
	mustEmbedUnimplementedCheckNodeServer()
}

// UnimplementedCheckNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckNodeServer struct{}

func (UnimplementedCheckNodeServer) Register(context.Context, *SlaveInfo) (*RegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedCheckNodeServer) SubscribePolicy(*SlaveID, grpc.ServerStreamingServer[Policy]) error {
	return status.Error(codes.Unimplemented, "method SubscribePolicy not implemented")
}
func (UnimplementedCheckNodeServer) ReportEvent(context.Context, *EventLog) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportEvent not implemented")
}
func (UnimplementedCheckNodeServer) Heartbeat(context.Context, *SlaveID) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCheckNodeServer) mustEmbedUnimplementedCheckNodeServer() {}
func (UnimplementedCheckNodeServer) testEmbeddedByValue()                   {}

// UnsafeCheckNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckNodeServer will
// result in compilation errors.
type UnsafeCheckNodeServer interface {
	mustEmbedUnimplementedCheckNodeServer()
}

func RegisterCheckNodeServer(s grpc.ServiceRegistrar, srv CheckNodeServer) {
	// If the following call panics, it indicates UnimplementedCheckNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckNode_ServiceDesc, srv)
}

func _CheckNode_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckNodeServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckNode_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckNodeServer).Register(ctx, req.(*SlaveInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckNode_SubscribePolicy_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SlaveID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CheckNodeServer).SubscribePolicy(m, &grpc.GenericServerStream[SlaveID, Policy]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CheckNode_SubscribePolicyServer = grpc.ServerStreamingServer[Policy]

func _CheckNode_ReportEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckNodeServer).ReportEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckNode_ReportEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckNodeServer).ReportEvent(ctx, req.(*EventLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckNode_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlaveID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckNodeServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckNode_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckNodeServer).Heartbeat(ctx, req.(*SlaveID))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckNode_ServiceDesc is the grpc.ServiceDesc for CheckNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "checknode.CheckNode",
	HandlerType: (*CheckNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _CheckNode_Register_Handler,
		},
		{
			MethodName: "ReportEvent",
			Handler:    _CheckNode_ReportEvent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CheckNode_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePolicy",
			Handler:       _CheckNode_SubscribePolicy_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
