[package]
name = "slave_pc"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.10"
prost = "0.12"
dotenvy = "0.15"
serde = { version = "1.0", features = ["derive"] }
windows = { version = "0.52", features = [
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_Foundation",
] }

[target.'cfg(target_os = "windows")'.dependencies]
wmi = "0.13"

[build-dependencies]
tonic-build = "0.10"